services:
  go_app:
    build: .
    networks:
      - go_caddy_network
    ports:
      - "3000:3000"

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - go_app
    networks:
      - go_caddy_network

networks:
  go_caddy_network:
    driver: bridge